# Proxy configuration for nginx
map $http_x_forwarded_proto $origin_proto {
    default $http_x_forwarded_proto;
    ""      $scheme;
}

# Map to detect POST to /auth/login
map "$request_uri:$request_method" $cms_login {
    default 0;
    "~^/auth/login$:POST" 1;
}
